os: linux
dist: bionic

install:
  - wget -qO- https://cmake.org/files/v3.17/cmake-3.17.0-Linux-x86_64.tar.gz | tar xvz

language: cpp
compiler:
  - gcc

before_script:
  - export CC=gcc-7
  - export CXX=g++-7

script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - ../cmake-3.17.0-Linux-x86_64/bin/cmake -DCMAKE_BUILD_TYPE=Debug ./../
  - ../cmake-3.17.0-Linux-x86_64/bin/cmake --build ./ --target bibParserTests -- -j 6